glib: pass poppler to gir libs.
Fixes cross compilation of gir in Void Linux

[ 85%] Generating Poppler-0.18.gir
g-ir-scanner: link: aarch64-linux-gnu-gcc -o /builddir/poppler-0.74.0/build/glib/tmp-introspectfs1jd4m9/Poppler-0.18 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv8-a -I/usr/aarch64-linux-gnu/usr/include /builddir/poppler-0.74.0/build/glib/tmp-introspectfs1jd4m9/Poppler-0.18.o -L. -Wl,-rpath,. -Wl,--no-as-needed -L/builddir/poppler-0.74.0/build -Wl,-rpath,/builddir/poppler-0.74.0/build -L/builddir/poppler-0.74.0/build/glib -Wl,-rpath,/builddir/poppler-0.74.0/build/glib -lpoppler-glib -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/aarch64-linux-gnu/usr/lib
/usr/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../aarch64-linux-gnu/bin/ld: warning: libpoppler.so.85, needed by ./libpoppler-glib.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../aarch64-linux-gnu/bin/ld: ./libpoppler-glib.so: undefined reference to `FormWidgetText::noSpellCheck() const'